### ISSUE TITLE
リリースまでのtodo

### ISSUE THREAD

**Issue by dustium162** [dustium162/footlog-frontend#7]
以下の要素をだいたい上から順番にやっていく。
また、本番環境への移行は、各ステップが終わってからではなく項目ごとに並行して進める。

【環境】
・development, test, productionごとにアクセスするAPIのURIを環境変数から取得するようにする。

【ユーザー情報の登録・認証機能(ログイン・ログアウトを含む)】
・メールを実際に送るようにする。

【Posts.js】
・投稿時にカードを削除(非表示)にするロジックを実装する。

【MyPage.js】
・ユーザー情報の編集機能を実装をする。
・応援しているチームの情報を記載する。

【ヘッダーコンテンツ】
・ログイン時・非ログイン時の表示・非表示コンテンツを整備する。

【フッターコンテンツ】
・コンテンツを記載する。

【レイアウト・デザイン】(命名規則・クォーテーション)
大体以下の順番
・ヘッダー
・フッター
・Posts.js
・MyPage.js
・Top.js

【管理者コンテンツ】
・試合情報の投稿ロジックを完成させる。
・その他の追加ロジックを完成させる。

**Comment by amount86** [comment]
2021-08-21現在

【環境】
・development, test, productionごとにアクセスするAPIのURIを環境変数から取得するようにする。

【MyPage.js】
・ユーザー情報の編集機能を実装をする。
・応援しているチームの情報を記載する。

【ヘッダーコンテンツ】
・ログイン時・非ログイン時の表示・非表示コンテンツを整備する。

【フッターコンテンツ】
・コンテンツを記載する。

【レイアウト・デザイン】(命名規則・クォーテーション)
大体以下の順番
・ヘッダー
・フッター
・Posts.js
・MyPage.js
・Top.js

【管理者コンテンツ】
・試合情報の投稿ロジックを完成させる。
・その他の追加ロジックを完成させる。

**Comment by amount86** [comment]
2021-09-04現在

- 管理者コンテンツを完成させる
- ユーザーのイメージAWS S3にアップロードする機能を実装をする。
- 管理者機能の表示・非表示を実装する。
- 投稿データのサニタイジング？

【レイアウト・デザイン】(命名規則・クォーテーション)
大体以下の順番
-  ヘッダー
-  フッター
-  Posts.js
-  MyPage.js
-  Top.js
