### ISSUE TITLE
投稿時にカードを削除(非表示)にするロジックについて

### ISSUE THREAD

**Issue by amount86** [dustium162/footlog-frontend#8]
Post.js上で新しく投稿したMatch情報（MatchInfoコンポーネント）を画面上からアニメーションを付加して削除するロジックを実装する必要がある。

現状、投稿後にMatchInfoコンポーネントを非表示にするロジックは実装できているが、消えたコンポーネントの場所に後続のコンポーネントがスライドされてない状況である。

![スクリーンショット 2021-08-21 14 06 07](https://user-images.githubusercontent.com/47709981/130311192-7fae20b2-2bac-451e-ac69-de0c893c9bd1.png)

これは、MatchInfoコンポーネントの上位に位置するPostsコンポーネント上のColコンポーネントで領域を確保しているためである。
そのため、これを解消するためには
（案１）Postsコンポーネントで確保している領域を、MatchInfoコンポーネントで確保するように変更する
（案２）MatchInfoでボタンを押されたことを検知したら、Postsコンポーネントに通知し、確保しているColコンポーネントを非表示にする
のどちらかが必要である。

**Comment by ToshihiroAsami** [comment]
Posts.js上のColコンポーネントをコメントアウトし、MatchInfo上のCardコンポーネント内にColコンポーネントをネストさせることで、うまく行っているように見えます。

【Posts.js】
```
        <Row xs={1} md={2} className="g-4 mx-0">
          {matches.map(match => (
            // <Col key={match.id}>
            // {match.id}
              <MatchInfo match={match} />
            // </Col>
          ))}
        </Row>
```
【MatchInfo.js】
```
  return (
    <div style={{display: display}}>
      <Col>　//これを追加
        <Card>
        略
        </Card>
     </Col>　//これを追加
   </div>
)
```

https://gyazo.com/b61b992a3a9fcce3c1bf536771e10165

**Comment by amount86** [comment]
確認しました。問題ないと思います。

**Comment by ToshihiroAsami** [comment]
追加したColを削除し、divをColに置換しても問題なく同様に動作することを確認しました。一旦はこれでやってみましょう。
引き続き、削除時のアニメーション作成に取り掛かります。
